### ISSUE TITLE
Question: How is this mod different?

### ISSUE THREAD

**Issue by SoopCanSam** [Skydust2B/PersistentPurchasesRewritten#2]
This looks like the same mod as this older one: https://thunderstore.io/c/lethal-company/p/TheBeeTeam/PersistentPurchases/

Are there differences?

**Comment by Skydust2B** [comment]
The last version of PersistentPurchases makes the game crash when the player is fired. I tried to rewrite the mod in a way that the game updates do not break it as much because I saw that the license allows it. It is based on the [rewrite branch from the original github](https://github.com/NotSoEpic/PeristentPurchases/tree/rewrite).

**Comment by SoopCanSam** [comment]
Thank you for explaining. No wonder my games were crashing...  Looking forward to using your mod instead.
